spring.application.name=rentnest-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/rentnest_db
spring.datasource.username=postgres
spring.datasource.password=YOUR_POSTGRES_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=rentnest_super_secret_key_change_this_later_123456789
jwt.expiration=86400000